Update readme & create publication overview
CLIMADA-project/climada_papers pull request #11
Opened 2024-06-12 06:58 UTC by sarah-hlsn

SCRUM [user story #125](https://tree.taiga.io/project/emanuel-schmid-climada/us/125?milestone=395053)

This pull request adjusts the information provided in the climada_papers repository, based on the new policy for making zenodo releases. Changes include:

New: `climada_papers_overview.md`
- move paper overview from README to new file & include zenodo DOI links in overview

Adjustments: `README.md `
- explain repository
- point external users to the overview 
- give internal users guidance for how to publish code and add to the overview

2024-06-24 12:05 UTC, luseverin requested changes
Thanks for the work! I made a few suggestions (typos and suggestions for rephrasing). Otherwise it looks all good to me.

2024-06-24 12:05 UTC, luseverin commented on README.md
> +This repository contains an overview of the publications an corresponding software components implemented in [CLIMADA Python](https://github.com/CLIMADA-project/climada_python). Please see [climada_p
```suggestion
This repository contains an overview of the publications and corresponding software components implemented in [CLIMADA Python](https://github.com/CLIMADA-project/climada_python). Please see [climada_papers_overview.md](./climada_papers_overview.md) for a list of publications and Zenodo DOI links.
```

2024-06-24 12:05 UTC, luseverin commented on README.md
> +* Update the paper overview in the climada_papers repository with the paper DOI and the code DOI from Zenodo (create a new row on top of the existing table)
```suggestion
* Update the paper overview [climada_papers_overview.md](./climada_papers_overview.md) in the climada_papers repository with the paper DOI and the code DOI from Zenodo (create a new row on top of the existing table)
```

2024-06-24 12:05 UTC, luseverin commented on climada_papers_overview.md
> +This file contains an overview of the publications an corresponding software components implemented in [CLIMADA Python](https://github.com/CLIMADA-project/climada_python).
```suggestion
This file contains an overview of the publications and corresponding software components implemented in [CLIMADA Python](https://github.com/CLIMADA-project/climada_python). 
```

2024-06-24 12:05 UTC, luseverin commented on climada_papers_overview.md
> +For authors: Please consult the [README](./README.md) on how to add to this overview before making any edits.
Maybe "to authors" or "to contributors" instead? The "for authors" sounds a bit weird to me but maybe that's just me. (also not so important, feel free to disregard)

2024-06-24 14:06 UTC, sarah-hlsn commented on climada_papers_overview.md
> +For authors: Please consult the [README](./README.md) on how to add to this overview before making any edits.
Yes I that's a good point, will change it accordingly :)

2024-06-26 13:24 UTC, spjuhel approved these changes

2024-06-27 09:19 UTC, merged