Hail damage model
CLIMADA-project/climada_papers pull request #8
Opened 2023-09-13 13:12 UTC by timschmi95

This pull request adds my recently submitted paper: An open-source radar-based hail damage model for buildings and cars. *Natural Hazards and Earth System Sciences*

2023-09-13 13:17 UTC, timschmi95 commented
Note that there are a somewhat large number of files, because the code uses functions from our (non-public) scClim repository. I think crucial is that the ReadMe is understandable, and helps a reader find the relevant code to 'replicate' results (with his/her own data).

2023-09-13 13:30 UTC, chahank commented
Thanks for the code and congratulation to the publication submission! 

I would have the following suggestions:

- Please update the README.md with the paper reference
- Add a table/text with the needed datasets, clearly linking those that are publicly available and where, as well as those that are not. For those that are not available, at least describe the required format so that someone can use their own data. In the notebook some datafiles are named, but not explained.
- Add more text to the notebooks to explain what is being done
- Add a more detailed overview explaining how the code should be used. I think that at the moment it is not plausible that someone could use this code to reproduce the results. But this is the goal in making the code available. There are so many files that it is very confusing.
- Some packages that are not part of CLIMADA 3.3 requirements seem to be used. Please update the python requirements. 
- the .py files are almost entirely uncommented. I would add at least overall comments to make them interpretable.

A general question from my side: is really ALL this code required to reproduce the results from the paper?

2023-09-13 13:54 UTC, chahank commented
Also, I would also propose that you make a test dataset to showcase the code for all datasets that are not publicly available.

2023-09-13 14:01 UTC, timschmi95 commented
Thanks for the comments. 
I'll add the paper reference, when the preprint is available. I can add some additional comments to the .py files and notebooks, but I think it should be possible to follow what's happening in the code with the current comments, even though it's of course not as well documented as a package. 

Re general question: It's pretty much all the code required, yes. There is some initial processing to get damage and exposure data to a consistent format for all insurances, but these files contain some insurance-specific information that cannot be publicly shared.. 

Re test dataset. I actually like the idea :) I hope I can find some time for it

2023-09-13 14:04 UTC, chahank commented
>I'll add the paper reference, when the preprint is available. I can add some additional comments to the .py files and notebooks, but I think it should be possible to follow what's happening in the code with the current comments, even though it's of course not as well documented as a package.

So, if I am a user, which files should I execute in which order? What datasets do I need? This is not clear. Also, in the scripts there are files with names that are not explained.

2023-09-13 14:48 UTC, chahank commented
Ideally, someone downloads all the above scripts. Then, this person knows exactly which datasets to download and where to put them. Then this person can simply execute the scripts in the prescribed order and reproduce your results.

2023-09-22 08:01 UTC, timschmi95 commented
So I added some additional comments explaining the paths of datasets, and some other comments.
The main change is an added Jupyter notebook that performs the calibration and evaluation by borrowing code from calibration_main.py and hail_main.py 
It runs with artificially created data of the same format as the (non-public) data I used for the calibration. I think this should help to reproduce the results with user-provided data. 
The required datasets (hazard, exposure, impact (spatially explicit)) are also shortly described in the ReadMe.

2024-01-24 09:38 UTC, leonie-villiger requested changes
Thank you for preparing and uploading the code belonging to your paper! 

I thoroughly checked the `ReadMe.md` and executed the `test_notebook.ipynb`. The two files provide a comprehensive overview of the repository and clear instructions of how to apply the main method (calibration and validation of vulnerability functions for hail events) of the paper. I also checked the files in the folder `notebooks` and found that it is clearly indicated which notebook reproduces which figure of the paper. I did not have time to look through all functionalities in `scClim` or `scripts`.

My comments are:
- correct typos and major issue (incomplete code to load hazard data) in the`text_notebook.ipynb`
- implement minor recommendations for text clarity in `ReadMe.md`
- remove `__pycache__` folder from the repository

Once these issues are addressed, I recommend merging-

2024-01-24 09:38 UTC, leonie-villiger commented on 202309_hail_damage_model/ReadMe.md
> +* **Exposure**: Tabular data of Exposure values and coordinates.  For format see *test_data/test_exp.nc*
```suggestion
* **Exposure**: Tabular data of exposure values and coordinates.  For format see *test_data/test_exp.csv*
```

2024-01-24 09:38 UTC, leonie-villiger commented on 202309_hail_damage_model/ReadMe.md
> +* **Damage**: Tabular data of reported damages **with spatial coordinates**. For format see *test_data/test_dmg.nc*
```suggestion
* **Damage**: Tabular data of reported damages **with spatial coordinates**. For format see *test_data/test_dmg.csv*
```

2024-01-24 09:38 UTC, leonie-villiger commented on 202309_hail_damage_model/ReadMe.md
> +
for consistency with description of other folders
```suggestion
### ./test_data/

```

2024-01-24 09:38 UTC, leonie-villiger commented on 202309_hail_damage_model/ReadMe.md
> +Jupyter notebooks to reproduce figures that appear in the paper
```suggestion
Jupyter notebooks to reproduce figures that appear in the paper.
```

2024-01-24 09:38 UTC, leonie-villiger commented on 202309_hail_damage_model/ReadMe.md
> +* *event_definition.py* performs the POH-based pre-processing of the building and car damage data
```suggestion
Python scripts used to process data and save intermediate results. In particular:
* *calibration_main.py* performs the spatially explicit calibration of vulnerability functions, saves impact function parameters and produces impact function plots.
* *hail_main.py* uses calibrated impact functions to estimate hail damages for different hazard-exposure combinations and saves skill scores.
* *event_definition.py* performs the POH-based pre-processing of the building and car damage data.
```

2024-01-24 09:38 UTC, leonie-villiger commented on .gitignore
the `__pycache__` folder (incl. three files) still appears in the repo. please delete and repush to remove it.

2024-01-24 09:38 UTC, leonie-villiger commented on 202309_hail_damage_model/test_notebook.ipynb
As discussed offline: issue loading the hazard dataset (incomplete code), some typos and two minor comments:
- Step 1: you define the variable `exposure = 'KGV' # "Kantonale Gebäudeversicherung“`; and you use `KGV` to create the `imp_measured`. Later, in step 2, you then use `exposure_type=„GVZ“. Since it is a dummy dataset you could use KGV in step 2 as well, right? If yes, I would do so to omit confusion.
- Step 5: add a comment why you do the distinction between pre and post 2012 events.

2024-01-24 10:24 UTC, timschmi95 commented on 202309_hail_damage_model/test_notebook.ipynb
Thanks, both is implemented

2024-01-24 10:31 UTC, merged