202311 crop hail damage footprint
CLIMADA-project/climada_papers pull request #9
Opened 2024-03-06 14:59 UTC by raphael-portmann

Code for the crop hail damage footprint model

Please check if the following scripts work (priority)

`run_damage_footprint_model.ipynb`
   - Notebook to apply the the hail damage footprint model and compute verification scores

`get_per_gridcell_data.py`
   - produces calibration files (*.p) in the subdirectory data/data_at_centroid/ that are used in many of the visualization scripts
   - suggested use: `python get_per_gridcell_data.py -croptypes wheat barley maize rapeseed grapevine -hazard_var MESHS -res 1 2 4 8 16 32`

You can also check the following skripts if you have time. They only work  after running `get_per_gridcell_data.py`, which creates a folder /data/data_at_centroids/

`plot_overview_map_Figure_1.ipynb`
   - Notebook to plot Figure 1 of the paper

`plot_skill_resolution_Figure_2.ipynb`
   - Notebook to reproduce Figure 2 of the paper

`plot_skill_metrics_single_event_Figures_3_4.ipynb`
   - Notebook to reproduce Figures 3 and 4 of the paper
   - Only works with hazard, exposure and damage as .netcdf files that are not provided via the Climada Data API. Available upon request.

`plot_skill_MESHS_threshold_Figure_5.ipynb`
   - Notebook to reproduce Figure 5 of the paper

`plot_skill_exposure_density_Figure_7.ipynb`
   - Skript to reproduce Figure 7 of the paper

`plot_performance_diagram.ipynb`
   - Notebook to produce a performance diagram

`plot_cropland_number_density_maps_Figure_A1.ipynb`
   - Notebook to reproduce Figure A1 of the paper 
   - Only works with hazard, exposure and damage as .netcdf files that are not provided via the Climada Data API. Available upon request.

`investigate_exposure_properties_Figures_A2_3.ipynb`
   - Notebook to plot Figures A2 and A3 and get the numbers mentionned in the paper

`plot_and_investigate_damage_exposure_mismatch.ipynb`
   - Notebook to reproduce numbers mentionned in Section 2.4 of the paper (uncertainty of random sampling and mismatch between damage and exposure data)
   - Only works with additional randomly sampled data (available upon request).

2024-03-13 07:46 UTC, leonie-villiger requested changes
Thank you for adding the code accompanying the pulication `Modelling crop hail damage footprints with single-polarization radar: The roles of spatial resolution, hail intensity, and cropland density`. 

I have run the tutorial `run_damage_footprint_model.ipynb` and checked the scripts and notebooks to reproduce the figures, tables and numbers discussed in the paper. I did not have time to look into all the functionalities in the `utility.py` and `calibration.py`, but trust that they are of good quality because they were developed and widely used in the scClim impact group. 

The code is clear and nicely commented, such that it is easy to understand and re-use. I have only a few minor comments that should be addressed before the pull request can be accepted. Please refer to the comments of the individual files for this.

2024-03-13 07:46 UTC, leonie-villiger commented on 202403_crop_hail_damage_footprint/README.md
> +- **Portmann R., Schmid T., Villiger L., Bresch D., Calanca P.** Modelling crop hail damage footprints with single-polarization radar: The roles of spatial resolution, hail intensity, and cropland de
```suggestion
- **Portmann R., Schmid T., Villiger L., Bresch D. N., Calanca P.** Modelling crop hail damage footprints with single-polarization radar: The roles of spatial resolution, hail intensity, and cropland density, submitted to Natural Hazards and Earth System Sciences.
```

2024-03-13 07:46 UTC, leonie-villiger commented on 202403_crop_hail_damage_footprint/get_per_gridcell_data.py
I get an error when running this script as suggested. The issue arises when I try loading the exposures from the data api: `ValueError: Valid exposures types are a subset of CLIMADA exposures types. Currently these types are supported: ['litpop', 'crop_production', 'ssp_population']`
It seems that `'crops'` is not yet properly defined as exposure types. 

The same happens when trying to load the hazard: `ValueError: Valid hazard types are a subset of CLIMADA hazard types. Currently these types are supported: ['river_flood', 'tropical_cyclone', 'storm_europe', 'relative_cropyield', 'wildfire', 'earthquake', 'flood']`

2024-03-13 07:46 UTC, leonie-villiger commented on 202403_crop_hail_damage_footprint/get_per_gridcell_data.py
> +        exposure[croptype] = client.get_exposures('crops', properties={'res_km': '1', 'crop': croptype})
```suggestion
        print(f'GET DATA FOR: {croptype}')
        exposure[croptype] = client.get_exposures('crops', properties={'res_km': '1', 'crop': croptype})
```

2024-03-13 07:46 UTC, leonie-villiger commented on 202403_crop_hail_damage_footprint/get_per_gridcell_data.py
> +            default = ['1','2','4','8','16','33'],
```suggestion
            default = ['1','2','4','8','16','32'],
```

2024-03-13 07:46 UTC, leonie-villiger commented on 202403_crop_hail_damage_footprint/get_per_gridcell_data.py
> +    # read standard data
```suggestion
    # read standard data with 1km spatial resolution
```

2024-03-13 07:46 UTC, leonie-villiger commented on 202403_crop_hail_damage_footprint/get_per_gridcell_data.py
> +
add comment that briefly explains what happens in the function `empirical_calibration_per_exposure`.

2024-03-13 07:46 UTC, leonie-villiger commented on 202403_crop_hail_damage_footprint/get_per_gridcell_data.py
> +Get damage, and exposure information at hazard centroid for each date.
In my understanding, more appropriate would be the following: 
```suggestion
Load exposure and damage data at 1km resolution. Get hazard information at exposure centroids for each date and each resolution.  
```

2024-03-13 07:46 UTC, leonie-villiger commented on 202403_crop_hail_damage_footprint/run_damage_footprint_model.ipynb
I tested the notebook and find it very easy to execute and follow. 

There is the issue with the `climada.conf` file (as discussed), which needs to be adapted manually/in the `climada_python`repository by adding "hail" to the "supported_hazard_types" and adding "crops" to the "supported_exposure_types". I know that you already are working on the solution....so that's ok, once solved. 

Else I have minor suggestion:
* ensure that all plots have meaningful axis labels and colorbar units. This ensures an easy take-up of the displayed information
* there is an "and" too much and an "is" missing in the markdown cell: "Now, we can read the damage data..."
* very minor comment regarding inconsistent styles: climada is sometimes written in capital letters and sometimes not. n_thresh is somtimes written in normal font other times in mathmode. would be nicer if all is the same.

2024-03-13 07:46 UTC, leonie-villiger commented on 202403_crop_hail_damage_footprint/calibration.py
> +    -1 used for disatances > threshold in point distances. If raster hazard,
```suggestion
    -1 used for distances > threshold in point distances. If raster hazard,
```

2024-03-13 07:46 UTC, leonie-villiger commented on 202403_crop_hail_damage_footprint/plot_overview_map_Figure_1.ipynb
Clear and easy to follow! Minor comment: You load quite some utilities and modules which are then not used in the script (at least not in the uncommented code)... in VScode they are shown in light gray. could remove for a clean script.

2024-03-13 07:46 UTC, leonie-villiger commented on 202403_crop_hail_damage_footprint/plot_skill_resolution_Figure_2.ipynb
Also clear and easy to follow. 
Minor comments: 
*there is an empty markdown cell that could be removed
*you don't use the modules `pickle, pd, cc`, which are loaded at the beginnin. could be removed

2024-03-13 07:46 UTC, leonie-villiger commented on 202403_crop_hail_damage_footprint/README.md
> +`plot_skill_exposure_density_Figure_67.ipynb`
```suggestion
`plot_skill_exposure_density_Figure_7.ipynb`
```

2024-03-13 07:46 UTC, leonie-villiger commented on 202403_crop_hail_damage_footprint/plot_performance_diagram.ipynb
What is the motivation to add this ipynb to the repo? This kind of plot is already illustrated in the `plot_performance_diagrams_Figure_6.py` and I think the functionality is also given in the function `plot_perfomrance_diagram` from the `utility` module. Maybe add some motivation in the Markdown of the given ipynb to clarify the purpose, else consider removing it.

2024-03-13 07:46 UTC, leonie-villiger commented on 202403_crop_hail_damage_footprint/investigate_exposure_properties_Figures_A2_3.ipynb
Please adapt the first markdown of the notebook to clarify that Figure A2 and A3 are produced in the notebook. Minor suggestion: I would also rename the notebook to `Figures_A2_A3.ipynb` for clarification (else it could be interpreted to have v3 of A2).

Also, I would be preferable to run the notebook once more with internet connection to omit the error messages `NoConnection` currently included in the output cells. 

After producing Figure A2, you write `For example the fraction of grid cells with only one field` and thereafter the wrong variable is printed (`n_n_field` instead of `n_one_field`), please adapt this.

2024-03-13 07:46 UTC, leonie-villiger commented on 202403_crop_hail_damage_footprint/get_skill_metrics_of_representative_examples_Table3.ipynb
Adapt title in first markdown cell. `Table 3`instead of `Table 1`

2024-03-15 14:22 UTC, raphael-portmann commented on 202403_crop_hail_damage_footprint/get_per_gridcell_data.py
this should now be solved as 'hail' and 'crops' has now been added to hazard and exposure types, respectively, in the default climada.conf file

2024-03-18 08:27 UTC, raphael-portmann commented on 202403_crop_hail_damage_footprint/get_per_gridcell_data.py
> +
done

2024-03-18 08:34 UTC, raphael-portmann commented on 202403_crop_hail_damage_footprint/plot_performance_diagram.ipynb
good point, its removed

2024-03-26 15:41 UTC, merged